DitHub/Controllers/DitsController.cs
using DitHub.Core.IRepositories;
using DitHub.Core.Models;
using DitHub.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DitHub.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class DitsController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly IUnitOfWork unit;

        public DitsController(UserManager<AppUser> userManager, IUnitOfWork unit)
        {
            this.userManager = userManager;
            this.unit = unit;
        }

        [Authorize]
        public IActionResult ArtistDits()
        {
            var list = unit.Dits.GetDitWithGenra(userManager.GetUserId(User));
            ViewData["Title"] = "My Dittes";
            return View(list);
        }

        [Authorize]
        public IActionResult ListFaveDit()
        {
            // FaveDits lookup is null because this action is for the user fave dits
            var id = userManager.GetUserId(User);
            var model = new ListDitViewModel()
            {
                Dits = unit.Dits.GetUserFave(id).ToList(),
                Title = "My Fave Dittes",
                SearchTerm = string.Empty,
                FaveDits = null,
                FolloweeL = unit.Followings.GetUserFollowee(id).ToLookup(f => f.FolloweeId),
            };
            return View("ListDit", model);

        }

        [Authorize(Policy= "Artist")]
        [HttpGet]
        public IActionResult Create()
        {
            var viewmodel = new CreateViewModel(unit.Genres.GetGenres())
            {
                Title = "Add a Ditte",
                Action = nameof(Create)
            };
            return View("DitForm", viewmodel);
        }

        [Authorize(Policy= "Artist")]
        [HttpPost]
        public IActionResult Create(CreateViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Genres = unit.Genres.GetGenres();
                return View("DitForm", viewModel);
            }
            var dit = new Dit(userManager.GetUserId(User), viewModel);

            unit.Dits.Add(dit);
            unit.Complete();
            return RedirectToAction("ArtistDits");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // check the user id before editing the dit
            var user = userManager.GetUserId(User);
            var dit = unit.Dits.GetDit(id);
            if (dit == null)
            {
                return NotFound();
            }
            if (dit.AppUserId != user)
            {
                return new UnauthorizedResult();
            }
            var viewmodel = new CreateViewModel(unit.Genres.GetGenres())
            {
                Venue = dit!.Venue,
                Date = dit!.Date.ToString("dd MMM yyyy"),
                Time = dit!.Date.ToString("HH:mm"),
                Genre = dit!.GenreId,
                Title = "Edit a Ditte",
                Action = nameof(Edit)
            };
            return View("DitForm", viewmodel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(CreateViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Genres = unit.Genres.GetGenres();
                return View("DitForm", viewModel);
            }
            var userId = userManager.GetUserId(User);
            //var dit = unit.Dits.GetDitWithFaves(viewModel.Id, userId);
            var dit = unit.Dits.GetDitWithFaves(viewModel.Id);
            if (dit == null)
            {
                return NotFound();
            }
            if (dit.AppUserId != userId)
            {
                return new UnauthorizedResult();
            }
            dit!.Update(viewModel);
            unit.Complete();
            return RedirectToAction("ArtistDits");
        }


        public IActionResult Details(int id)
        {
            var dit = unit.Dits.GetDit(id);
            if (dit == null)
            {
                return NotFound();
            }
            var details = new DetailsViewModel()
            {
                Dit = dit!,
            };
            var userId = userManager.GetUserId(User);
            if (userId != null)
            {
                details.Following = unit.Followings.IsInFaveA(dit.AppUserId, userId);
                details.Infave = unit.Favedits.IsInFaveD(dit.Id, userId);
            }
            return View(details);
        }
    }
}

DitHub/Views/Shared/ListDit.cshtml
@model ListDitViewModel

@{
    ViewData["Title"] = @Model.Title;
}
<h2 class="mb-3">@Model.Title</h2>

<form method="post" asp-action="Search" asp-controller="Home">
    <div class="input-group mb-3">
        <div id="searchdiv" class="form-floating" tabindex="0">
            <input type="text" class="form-control" aria-label="Seaech Dittes"
                   aria-describedby="addon" asp-for="@Model.SearchTerm" id="searchin">
            <label for="search">Search Dittes:</label>
        </div>
        <button class="input-group-text" id="addon" type="submit">
            <i class="bi bi-search"></i>
        </button>
    </div>
</form>
<ul class="listDA">
    @foreach (var item in Model.Dits)
    {
        <li class="d-flex">
            <div class="number flex-shrink-0">
                <div class="upN">@item.Date.ToString("MMM")</div>
                <div class="downN">@item.Date.ToString("dd")</div>
            </div>
            <div class="details flex-fill">
                <a asp-action="Details" asp-controller="Dits" asp-route-id="@item.Id" class="artist">
                    @item.AppUser.Name
                </a>
                <span class="downD">@item.Genre.Name</span>
            </div>
            <div class="ms-auto">
                @if (User.Identity!.IsAuthenticated)
                {
                    <button data-Feeid="@item.AppUserId" class="A btn btn-sm p-1">
                        @(Model.FolloweeL!.Contains(item.AppUserId) ? "A Is + Fave.":"+ Fave Artist?")
                    </button>
                    if (Model.Title == "Home Dittes")
                    {
                        <button data-ditid="@item.Id" class="D btn btn-sm p-1">
                            @(Model.FaveDits!.Contains(item.Id) ? "D Is + Fave.":"+ Fave Ditty?")
                        </button>
                    }
                    if (item.RemoveFlag)
                    {
                        <span class="badge bg-warning text-dark p-2">Removed</span>
                    }
                    else
                    {
                        <span class="badge bg-info text-dark p-2">Active</span>

                    }
                }
            </div>
        </li>
    }
</ul>
@section scripts
{
    <script>
        $(document).ready(function () {
            DitController.val(".listDA");
            FollowController.val(".listDA")
        })
    </script>
}

DitHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<meta name="google-signin-client_id" content="285329013980-ce2ihslcqd7ldph0c8nr5h862p7gpri4.apps.googleusercontent.com">*@
    <title>@ViewData["Title"] - DitHub</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/style.css" rel="stylesheet" asp-append-version="true" />
        <link href="https://fonts.googleapis.com/css2?family=Quintessential&display=swap" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link href="https://fonts.googleapis.com/css2?family=Quintessential&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="visually-hidden"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        <link href="~/lib/style.min.css" rel="stylesheet" />
    </environment>
    @*<script src="~/lib/modernizr.min.js"></script>*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DitHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dits" asp-action="Create">Create Ditty</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - DitHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bundle.js" type="text/javascript" asp-append-version="true"></script>
        @* a bundle of bootstrap & propper *@
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/lib/bootdep.js" type="text/javascript"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"
                asp-fallback-src="~/lib/jqurey/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="~/lib/bundle.min.js"></script>
        @* a bundle of bootstrap & propper *@
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.bootstrap"></script>
        <script src="~/lib/bootdep.min.js"></script>
    </environment>
    @await RenderSectionAsync("Scripts", required: false)
    <script type="text/template" id="notifi-temp">
        <ul class="NP">
            <% _.each(notifis,function(notifi) { %>
            <% if (notifi.statue == "new") {
            $("ul.NP>li").attr("id", "new")
            console.log("new");
            }
            if (notifi.statue == "old") {
            $("ul.NP>li").css("background-color", "red")
            console.log("old");
            }%>
            <% if (notifi.type == 2) { %>
            <li>
                <span class="N-name"><%= notifi.dit.appUser.name %></span> canceled the dit at venue <%= notifi.dit.venue %> at <%= moment(notifi.dit.date).format("D MMM HH:mm") %>
            </li>
            <% } %>
            <% if (notifi.type == 3) { %>
            <% console.log(notifi) %>
            <li>
                <% if (notifi.changed == "none") { %>
                <span class="N-name">
                    <%= notifi.dit.appUser.name %>
                </span> updated the dit
                <% } %>
                <% if (notifi.changed == "date") { %>
                <span class="N-name">
                    <%= notifi.dit.appUser.name %>
                </span> updated the dit from date <%= moment(notifi.dateTime0).format("D MMM HH:mm") %> to <%= moment(notifi.dit.date).format("D MMM HH:mm") %>
                <% } %>
                <% if (notifi.changed == "venue") { %>
                <span class="N-name">
                    <%= notifi.dit.appUser.name %>
                </span> updated the dit from venue <%= notifi.venue0 %> to <%= notifi.dit.venue %>
                <% } %>
                <% if (notifi.changed == "both") { %>
                <span class="N-name">
                    <%= notifi.dit.appUser.name %>
                </span> updated the dit from <%= moment(notifi.dateTime0).format("D MMM HH:mm") %>/<%= notifi.venue0 %> to <%= moment(notifi.dit.date).format("D MMM HH:mm") %>/<%= notifi.dit.venue %>
                <% } %>
            </li>
            <% }%>
            <% }) %>
        </ul>
    </script>
    <script>
        $(document).ready(function () {
            $.getJSON("/api/notifications", function (notifications) {
                if (notifications.length == 0)
                    return;
                $(".N")
                    .text(notifications.length)
                    .addClass("animate__animated animate__bounce");
                $('a.bi').popover({
                    placement: 'bottom',
                    container: 'body',
                    html: true,
                    trigger: "click focus",
                    template: '<div class="popover p-line" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',
                    content:
                        function () {
                            var compiled = _.template($("#notifi-temp").html());
                            return compiled({ notifis: notifications });
                        },
                })
                    .on("shown.bs.popover", function () {
                        $.post("/api/notifications/makeread")
                            .done(function () {
                                console.log("marked");
                                $(".N").text("0");
                            });
                    })
                    .click(function (evt) {
                        evt.stopPropagation();
                        $(this).popover('show');
                    });
            }
            );
            $('html').click(function () {
                $('a.bi').popover('hide')
            });
        });
    </script>
</body>
</html>